package codespaces

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)


// ===========================================
// SSH Config Types
// ===========================================

// sshConfig holds SSH connection details for a codespace derived from
// the OpenSSH config generated by `gh codespace ssh --config`.
type sshConfig struct {
	configPath string // absolute path to the SSH config file
	host       string // SSH host alias (e.g. "cs.codespace-name.abc123")
}

// ===========================================
// Path Helpers
// ===========================================

// configPathForWorkspace returns the SSH config file path for an instance.
// Config is stored alongside the instance workspace at:
//
//	~/.fleet/workspaces/<fleet>/<instance>/ssh-config
func configPathForWorkspace(workspaceDir string) string {
	return filepath.Join(filepath.Dir(workspaceDir), "ssh-config")
}

// ===========================================
// Config Parsing
// ===========================================

// parseSSHConfigHost extracts the SSH Host alias from OpenSSH config
// output. When csName is non-empty, it prefers a Host entry that
// contains the codespace name. Falls back to the first non-wildcard
// Host entry.
func parseSSHConfigHost(config, csName string) string {
	var firstHost string
	for _, line := range strings.Split(config, "\n") {
		trimmed := strings.TrimSpace(line)
		if !strings.HasPrefix(trimmed, "Host ") {
			continue
		}
		host := strings.TrimSpace(strings.TrimPrefix(trimmed, "Host "))
		if host == "" || host == "*" {
			continue
		}
		if firstHost == "" {
			firstHost = host
		}
		if csName != "" && strings.Contains(host, csName) {
			return host
		}
	}
	return firstHost
}

// ===========================================
// Command Building
// ===========================================

// nativeSSHArgs builds arguments for a native `ssh` command using the
// generated OpenSSH config. allocPTY adds the -t flag for interactive
// commands that need a pseudo-terminal (e.g. tmux).
func nativeSSHArgs(config *sshConfig, command []string, allocPTY bool) []string {
	args := []string{"-F", config.configPath}
	if allocPTY {
		args = append(args, "-t")
	}
	// Forward SSH agent when available on the host.
	if os.Getenv("SSH_AUTH_SOCK") != "" {
		args = append(args, "-A")
	}
	args = append(args, config.host)
	if len(command) == 0 {
		return args
	}
	args = append(args, "--")
	// Collapse "sh -c 'script'" into just "script" since SSH already
	// wraps the remote command in a shell.
	if len(command) == 3 && command[0] == "sh" && command[1] == "-c" {
		args = append(args, command[2])
	} else {
		args = append(args, command...)
	}
	return args
}

// ===========================================
// Config Generation
// ===========================================

// generateSSHConfig runs `gh codespace ssh --config` for a codespace,
// writes the output to the instance directory, and caches the result.
func (codespacesBackend *CodespacesBackend) generateSSHConfig(csName, workspaceDir string) (*sshConfig, error) {
	out, err := exec.Command("gh", "codespace", "ssh", "--config", "-c", csName).Output()
	if err != nil {
		return nil, fmt.Errorf("gh codespace ssh --config: %w", err)
	}

	host := parseSSHConfigHost(string(out), csName)
	if host == "" {
		return nil, fmt.Errorf("could not parse SSH host alias from config output")
	}

	configPath := configPathForWorkspace(workspaceDir)
	if err := os.MkdirAll(filepath.Dir(configPath), 0755); err != nil {
		return nil, fmt.Errorf("creating config directory: %w", err)
	}
	if err := os.WriteFile(configPath, out, 0600); err != nil {
		return nil, fmt.Errorf("writing SSH config: %w", err)
	}

	config := &sshConfig{configPath: configPath, host: host}
	codespacesBackend.sshConfigs[csName] = *config
	return config, nil
}

// loadSSHConfig reads an existing SSH config file from disk and caches it.
// Returns nil if the file does not exist or cannot be parsed.
func (codespacesBackend *CodespacesBackend) loadSSHConfig(csName, workspaceDir string) *sshConfig {
	configPath := configPathForWorkspace(workspaceDir)
	data, err := os.ReadFile(configPath)
	if err != nil {
		return nil
	}

	host := parseSSHConfigHost(string(data), csName)
	if host == "" {
		return nil
	}

	config := &sshConfig{configPath: configPath, host: host}
	codespacesBackend.sshConfigs[csName] = *config
	return config
}

// ===========================================
// SSH Command Factory
// ===========================================

// sshCommand returns an *exec.Cmd for running a command inside a
// codespace. Uses native SSH with the generated OpenSSH config when
// available, which provides proper PTY allocation for interactive
// commands like tmux. Falls back to `gh codespace ssh` when no config
// is cached.
func (codespacesBackend *CodespacesBackend) sshCommand(csName string, command []string, allocPTY bool) *exec.Cmd {
	if config, ok := codespacesBackend.sshConfigs[csName]; ok {
		args := nativeSSHArgs(&config, command, allocPTY)
		return exec.Command("ssh", args...)
	}
	// Fallback: gh codespace ssh (no PTY for remote commands).
	args := sshArgs(csName, command)
	return exec.Command("gh", args...)
}
